#!/usr/bin/env python3
"""Scan the upstream Halo decomp and report per-module platform dependencies.

Usage: tools/audit_platform_deps.py [UPSTREAM_DIR] > docs/PORTING_AUDIT.md
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

root = Path(sys.argv[1] if len(sys.argv) > 1 else "upstream")
CATS = {
    "D3D8/GPU": r"d3d8|IDirect3D|D3DX|D3DDEVICE|D3DFMT|\bD3D[A-Z]",
    "inline x86 asm": r"\b__asm\b|\b_asm\b",
    "Xbox/Win API": r"windows\.h|xtl\.h|\bXAPI|\bXbox|\bXBOX|\bXGetDevices|\bXInput",
    "Audio (DSound)": r"dsound|DirectSound|IDirectSound",
    "Bink video": r"\bbink\b|\bBink[A-Z]",
    "MSVC-isms": r"__declspec|__fastcall|__stdcall|__cdecl|__int64|__forceinline",
}
cats = {k: re.compile(v, re.I if k != "MSVC-isms" else 0) for k, v in CATS.items()}
exts = {".c", ".cpp", ".h", ".inc"}

rows = defaultdict(lambda: defaultdict(int))
loc = defaultdict(int)
files = defaultdict(int)
for sub in ("source", "libs"):
    for p in sorted((root / sub).rglob("*")):
        if p.suffix not in exts:
            continue
        mod = "/".join(p.relative_to(root).parts[:2])
        text = p.read_text(errors="replace")
        loc[mod] += text.count("\n")
        files[mod] += 1
        for name, rx in cats.items():
            if rx.search(text):
                rows[mod][name] += 1

names = list(CATS)
print("# Platform dependency audit\n")
print("Generated by `tools/audit_platform_deps.py`. Cells are the number of files in the module that match the category.\n")
print("| module | files | LOC | " + " | ".join(names) + " |")
print("|---|---|---|" + "---|" * len(names))
for mod in sorted(loc):
    print(f"| `{mod}` | {files[mod]} | {loc[mod]} | " + " | ".join(str(rows[mod].get(n, "")) or "" for n in names) + " |")
print(f"\nTotal: {sum(files.values())} files, {sum(loc.values())} LOC")
