#!/usr/bin/env python3
"""Generate compat/halo_struct_forwards.h: `struct X;` for every struct tag in the upstream tree.

MSVC gives a struct first named in a prototype's parameter list file scope; GCC gives it prototype
scope, which makes later declarations "conflicting types". Forward-declaring every tag up front fixes that.
Usage: tools/gen_struct_forwards.py UPSTREAM_DIR
"""
import re, sys
from pathlib import Path

root = Path(sys.argv[1])
structs, unions, enums = set(), set(), set()
rx = re.compile(r"\b(struct|union|enum)\s+([A-Za-z_]\w*)")
for p in list((root / "source").rglob("*.[ch]")) + list((root / "source").rglob("*.cpp")):
    if "libtiff" in str(p) or "zlib" in str(p): continue
    for kind, name in rx.findall(p.read_text(errors="replace")):
        {"struct": structs, "union": unions, "enum": enums}[kind].add(name)
only_struct = sorted(structs - unions - enums)
only_union = sorted(unions - structs - enums)
out = ["/* Generated by tools/gen_struct_forwards.py: do not edit. */", "#ifndef HALO_STRUCT_FORWARDS_H", "#define HALO_STRUCT_FORWARDS_H"]
out += [f"struct {n};" for n in only_struct]
out += [f"union {n};" for n in only_union]
out += ["#endif", ""]
Path(sys.argv[2] if len(sys.argv) > 2 else "compat/halo_struct_forwards.h").write_text("\n".join(out))
print(f"{len(only_struct)} struct + {len(only_union)} union tags ({len(structs & unions)} struct/union name clashes skipped)")
